export const UsecaseSymbols = {
  User: {
    CreateUserUsecase: Symbol.for('CreateUserUsecase'),
    FindUserByIdUsecase: Symbol.for('FindUserByIdUsecase'),
    FindUserByEmailUsecase: Symbol.for('FindUserByEmailUsecase'),
    UpdateUserUsecase: Symbol.for('UpdateUserUsecase'),
    DeleteUserUsecase: Symbol.for('DeleteUserUsecase'),
    GetUsersUsecase: Symbol.for('GetUsersUsecase'),
  },
  Otp: {
    SendOtpUsecase: Symbol.for('SendOtpUsecase'),
    VerifyOtpUsecase: Symbol.for('VerifyOtpUsecase'),
  },
  Auth: {
    RegisterUserUsecase: Symbol.for('RegisterUserUsecase'),
    VerifyUserUsecase: Symbol.for('VerifyUserUsecase'),
    LoginUserUsecase: Symbol.for('LoginUserUsecase'),
    RefreshTokenUsecase: Symbol.for('RefreshTokenUsecase'),
    GetMeUsecase: Symbol.for('GetMeUsecase'),
  },
  Permission: {
    CreatePermissionUsecase: Symbol.for('CreatePermissionUsecase'),
    GetPermissionsUsecase: Symbol.for('GetPermissionsUsecase'),
    FindPermissionByIdUsecase: Symbol.for('FindPermissionByIdUsecase'),
    UpdatePermissionUsecase: Symbol.for('UpdatePermissionUsecase'),
    DeletePermissionUsecase: Symbol.for('DeletePermissionUsecase'),
  },
  Role: {
    CreateRoleUsecase: Symbol.for('CreateRoleUsecase'),
    GetRolesUsecase: Symbol.for('GetRolesUsecase'),
    FindRoleByIdUsecase: Symbol.for('FindRoleByIdUsecase'),
    UpdateRoleUsecase: Symbol.for('UpdateRoleUsecase'),
    DeleteRoleUsecase: Symbol.for('DeleteRoleUsecase'),
  },
  Membership: {
    CreateMembershipUsecase: Symbol.for('CreateMembershipUsecase'),
    GetMembershipsUsecase: Symbol.for('GetMembershipsUsecase'),
    GetTeamMembersUsecase: Symbol.for('GetTeamMembersUsecase'),
    FindMembershipByIdUsecase: Symbol.for('FindMembershipByIdUsecase'),
    UpdateMembershipUsecase: Symbol.for('UpdateMembershipUsecase'),
    DeleteMembershipUsecase: Symbol.for('DeleteMembershipUsecase'),
  },
  Team: {
    CreateTeamUsecase: Symbol.for('CreateTeamUsecase'),
    GetTeamsUsecase: Symbol.for('GetTeamsUsecase'),
    FindTeamByIdUsecase: Symbol.for('FindTeamByIdUsecase'),
    UpdateTeamUsecase: Symbol.for('UpdateTeamUsecase'),
    DeleteTeamUsecase: Symbol.for('DeleteTeamUsecase'),
  },
  Project: {
    CreateProjectUsecase: Symbol.for('CreateProjectUsecase'),
    GetProjectsUsecase: Symbol.for('GetProjectsUsecase'),
    FindProjectByIdUsecase: Symbol.for('FindProjectByIdUsecase'),
    UpdateProjectUsecase: Symbol.for('UpdateProjectUsecase'),
    DeleteProjectUsecase: Symbol.for('DeleteProjectUsecase'),
  },
  Board: {
    CreateBoardUsecase: Symbol.for('CreateBoardUsecase'),
    GetBoardsUsecase: Symbol.for('GetBoardsUsecase'),
    FindBoardByIdUsecase: Symbol.for('FindBoardByIdUsecase'),
    UpdateBoardUsecase: Symbol.for('UpdateBoardUsecase'),
    DeleteBoardUsecase: Symbol.for('DeleteBoardUsecase'),
  },
};
